### ISSUE TITLE
support for <a> tags

### ISSUE THREAD

**Issue by benhalpern** [dburrows/draft-js-basic-html-editor#1]
Hey I'm just checking out this project and I'm wondering if you have plans to get link tags working within the project.

**Comment by dburrows** [comment]
Yes, just playing around with it at the moment but next steps are basic inline tags, then links & images - will add a README today with some detail

**Comment by benhalpern** [comment]
Awesome. I'll be following along and help where I can.

**Comment by dburrows** [comment]
Ok, basic support is in 0402bffc94a1335b250411ac7f8ff7f87128ada3, will probably revisit this at some point as the interface isn't great
