### ISSUE TITLE
Overlapping inline style ranges.

### ISSUE THREAD

**Issue by thezanke** [dburrows/draft-js-basic-html-editor#10]
Inner inline style tags need to terminate before an outer tag terminates, and then must be reopened in the proper order.

For instance:

In the sentence "The quick brown fox jumps over the lazy dog.", if you highlight "quick brown fox jumps over" and apply bold and then highlight "jumps over the lazy" and apply italics the editor generates invalid HTML.

In this case, the editor generates:

```
The <strong>quick brown fox <em>jumps over</strong> the lazy</em> dog.
```

Instead of:

```
The <strong>quick brown fox <em>jumps over</em></strong><em> the lazy</em> dog.
```

**Comment by dburrows** [comment]
Sorry for non-reply, was on holiday. Thanks for reporting, will have a look at it this week, may take a while as we'll need to track nesting in the output processing.

**Comment by thezanke** [comment]
I actually ended up finding a pretty good way to do draft-to-html based on how the docs describe that they do it internally. I don't use raw anymore. I get the text and iterate character-by-character. For each character I pull the inline styles for that position and any time there's a new combination of styles I create a new element. I wrote a fake document api to allow me to manipulate it as if it was actual document elements but they are really just objects that generate html strings when casted to string. It was a totally different approach than my first attempt at cracking the draft-to-html thing (which looked similar to yours in concept).

If you're interested in how it works check draftToHTML, applyInlineStyles, and Elemental utils here: https://github.com/thezanke/thezanke-react-express-mongo/tree/dev/app/utils

**Comment by dburrows** [comment]
In perfect timing I saw your comment about 10 seconds after fixing it in commit 
2b1a4609f55e2c43fa84a1c50e795f9b1c8f8461, not that happy about the code but it seems to work!

Thanks for updating the issue btw, will definitely have a look at your solution, sounds interesting and my solution isn't very elegant but may be more performant on very long docs with not much markup (he says, trying to think of something good about his code ;)
