### ISSUE TITLE
Is the angularjs refrence in your lisence correct?

### ISSUE THREAD

**Issue by tarjei** [dburrows/draft-js-basic-html-editor#13]
See https://github.com/dburrows/draft-js-basic-html-editor/blob/master/LICENSE#L3

**Comment by dburrows** [comment]
Weird, no idea where that came from! Will remove

**Comment by dburrows** [comment]
Fixed in https://github.com/dburrows/draft-js-basic-html-editor/commit/e24e57d195b3d9a970a3e155b118e4a1cb93cd08

**Comment by tarjei** [comment]
:)

2016-06-20 18:16 GMT+02:00 David Burrows notifications@github.com:

> Weird, no idea where that came from! Will remove
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dburrows/draft-js-basic-html-editor/issues/13#issuecomment-227191275,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAM5P638cvhhQck-4leLpB8PAGlZzP33ks5qNrzqgaJpZM4I5KAP
> .

## 

---

Tarjei Huse
Mobil: 920 63 413
