### ISSUE TITLE
Query: How does this example handle pasted content

### ISSUE THREAD

**Issue by zhuscat** [dburrows/draft-js-basic-html-editor#16]

**Comment by zhuscat** [comment]
Sorry, I use my smart to submit this issue. And I touch the "go" button by accident, which I thought was a new line button.
My problem is: I learn draft.js use examples provided by Facebook, and I found when I paste content I copy from website, the format is wrong. There are no new paragraphs. And your component handle this correctly. I read your code, but I have not found out why your component works. Thank you for your help!!!

**Comment by zhuscat** [comment]
The example provided by Facebook is rich.html

**Comment by dburrows** [comment]
Can you provide an example of the content that works? It may just be a difference between the current version of Draftjs and the one this repo is running. I haven't updated it in a while.

**Comment by zhuscat** [comment]
@dburrows I change the version of `draft.js` to `0.6.0`，and I found the format is good in this version... I'm wondering if it is a BUG in the latest version. My test content is from [test content](http://news.sohu.com/20160830/n466810191.shtml). It's in Chinese.

**Comment by zhuscat** [comment]
@dburrows Here is the difference.
<img width="1262" alt="2016-08-31 11 32 32" src="https://cloud.githubusercontent.com/assets/14963619/18115050/bae747a0-6f6e-11e6-8099-92d2d615ed11.png">
<img width="695" alt="2016-08-31 11 32 45" src="https://cloud.githubusercontent.com/assets/14963619/18115054/be02955c-6f6e-11e6-8a9e-ea756e7ccedc.png">

The first picture shows the behavior of your component.

**Comment by dburrows** [comment]
Yes, looks like an issue with Draft.js, I'm going to close this, I would report your issue on the main Draft repo if you're still having problems.
