### ISSUE TITLE
Browserify Failed!: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by martijnbac** [dburrows/draft-js-basic-html-editor#4]
This looks great! Except when I try to bundle my code using Browserify, I get the following error:

```
Browserify Failed!: 'import' and 'export' may appear only with 'sourceType: module'

/Users/martijnbac/Code/admin-react/node_modules/draft-js-basic-html-editor/src/BasicHtmlEditor.js:1
import React from 'react';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

I just started learning React, so I could be doing something wrong.

Thanks!

**Comment by dburrows** [comment]
Aha, yes - the lib is an ES6 module so will need to be compiled if your not using ES6, it does mention this in the README now but could probably be a bit more explicit.

I don't user Browserify these days, is there any chance you can fix this by enabing ES6 in Browserify for this lib? If not I can try and make a Browserify compatible build but that may take a while

**Comment by martijnbac** [comment]
I'm using ES6, Babel and Browserify has ES6 enabled by default. Maybe I'm overlooking something; my knowledge on this area is limited. Would be great to have a Browerify compatible build If the problem lies within this lib.  But because I'm not sure, maybe someone can confirm that the problem can't be fixed by using different Browserify settings.

**Comment by dburrows** [comment]
Ok, I had a look at the Browserify docs and have added some config for it - try pulling the new version 1.0.1 and see if it works now

**Comment by martijnbac** [comment]
Thanks! Almost there :-) The Lodash library seems to be missing. Required by src/utiles/processInlineStylesAndEntities.js. The lib compiles when I comment out the import-lines in that file, but then I'm getting an error in the browser console (Uncaught ReferenceError: sortBy is not defined)

**Comment by dburrows** [comment]
Fixed the missing lodash - pull v1.0.2 and that should be it

**Comment by martijnbac** [comment]
Great, everything is working now. Thanks!

**Comment by dburrows** [comment]
No problem, thanks for helping me get the module into a usable state :+1:
